# Generated by Django 3.2.7 on 2021-09-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_overunderline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='overunderline',
            unique_together={('team', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together={('player', 'team', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='playerscore',
            unique_together={('player', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('league', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('league', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='teamrecord',
            unique_together={('team', 'season')},
        ),
    ]
