# Generated by Django 3.2.7 on 2021-09-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_auto_20210912_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(default='xxx', max_length=10),
            preserve_default=False,
        ),
    ]
