# Generated by Django 3.2.7 on 2021-09-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_team_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='score',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
