# Generated by Django 3.2.7 on 2023-04-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0009_auto_20230402_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='games_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='games_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
