# Generated by Django 5.1.7 on 2025-04-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0012_alter_overunderline_line'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pick',
            name='pickorder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pick',
            name='points',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together={('player', 'team', 'season', 'pickorder')},
        ),
    ]
