# Generated by Django 5.1.7 on 2025-04-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0013_alter_pick_unique_together_pick_pickorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='ties_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
